---
version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=record-appender
    ports:
      - 5432:5432
    healthcheck:
      # https://github.com/peter-evans/docker-compose-healthcheck/issues/16
      test: ["CMD", "pg_isready", "q", "-U", "postgres", "-d", "record-appender"]
      interval: 10s
      timeout: 5s
      retries: 5
